name: run

on:
  push:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  run:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2

      - name: Run main.sh
        run: bash main.sh
